version: 2.1

jobs:
  build:

    docker:
      - image: circleci/buildpack-deps:trusty

    parameters:
      load_docker_cache:
        type: boolean
      save_docker_cache:
        type: boolean
      run_tests_smoke:
        type: boolean
        default: false
      run_tests_core:
        type: boolean
        default: false
      run_tests_internal:
        type: boolean
        default: false
      run_tests_contrib:
        type: boolean
        default: false
      run_tests_integration:
        type: boolean
        default: false

    steps:

      - checkout

      - setup_remote_docker

      - when:
          condition: <<parameters.load_docker_cache>>
          steps:
            - restore_cache:
                keys:
                  - v1-docker-images
            - run:
                name: Load Docker layers cache
                command: |
                  docker load -i ~/docker-layers-cache.tar || true

      - run:
          name: Build the stack
          command: docker-compose -f docker-compose.yml build
          working_directory: scripts/spcgeonode/

      - when:
          condition: <<parameters.save_docker_cache>>
          steps:
            - run:
                name: Save Docker layers cache
                command: |
                  rm -f ~/docker-layers-cache.tar
                  docker save -o ~/docker-layers-cache.tar $(docker images -a --format "{{.ID}}")
                when: always
            - save_cache:
                key: v1-docker-images-{{ epoch }}
                paths:
                  - ~/docker-layers-cache.tar
                when: always

      - run:
          name: Start the stack
          command: docker-compose -f docker-compose.yml up -d --build
          working_directory: scripts/spcgeonode/

      - run:
          name: Wait for everything to start...
          command: |
            n=1
            m=60
            until [ $n -gt $m ]
            do
              sleep 60
              DJANGO_STATUS=$(docker inspect --format="{{json .State.Health.Status}}" spcgeonode_django_1)
              GEOSERVER_STATUS=$(docker inspect --format="{{json .State.Health.Status}}" spcgeonode_geoserver_1)
              echo ""
              echo "Waited $n min (out of $m min)"
              if [[ $DJANGO_STATUS == '"healthy"' ]] && [[ $GEOSERVER_STATUS == '"healthy"' ]]; then
                break
              fi
              echo "Not healthy yet..."
              docker ps
              n=$[$n+1]
            done
            [[ $DJANGO_STATUS == '"healthy"' ]] && [[ $GEOSERVER_STATUS == '"healthy"' ]];

      - run:
          name: Show state (debug)
          command: docker ps
          when: on_fail

      - run:
          name: Geoserver logs (debug)
          command: docker logs spcgeonode_geoserver_1 --tail 500
          when: on_fail

      - run:
          name: Django logs (debug)
          command: docker logs spcgeonode_django_1 --tail 500
          when: on_fail

      - when:
          condition: <<parameters.run_tests_smoke>>
          steps:
            - run:
                name: Run smoke tests
                command: |
                  docker-compose exec django bash -c 'python manage.py test geonode.tests.smoke'
                working_directory: scripts/spcgeonode/

      - when:
          condition: <<parameters.run_tests_core>>
          steps:
            - run:
                name: Run core applications tests
                command: |
                  docker-compose exec django bash -c 'python manage.py test $(python -c "import sys;from geonode import settings;sys.stdout.write('\'' '\''.join([a for a in settings.GEONODE_CORE_APPS]))")'
                working_directory: scripts/spcgeonode/

      - when:
          condition: <<parameters.run_tests_internal>>
          steps:
            - run:
                name: Run internal applications tests
                command: |
                  docker-compose exec django bash -c 'python manage.py test $(python -c "import sys;from geonode import settings;sys.stdout.write('\'' '\''.join([a for a in settings.GEONODE_INTERNAL_APPS]))")'
                working_directory: scripts/spcgeonode/

      - when:
          condition: <<parameters.run_tests_contrib>>
          steps:
            - run:
                name: Run contrib applications tests
                command: |
                  docker-compose exec django bash -c 'python manage.py test $(python -c "import sys;from geonode import settings;sys.stdout.write('\'' '\''.join([a for a in settings.GEONODE_CONTRIB_APPS]))")'
                working_directory: scripts/spcgeonode/

      - when:
          condition: <<parameters.run_tests_integration>>
          steps:
            - run:
                name: Run integrations tests
                command: |
                  docker-compose exec django bash -c 'python manage.py test geonode.tests.integration'
                working_directory: scripts/spcgeonode/

workflows:

  commit:
    jobs:
      - build:
          name: setup
          load_docker_cache: true
          save_docker_cache: true
          run_tests_smoke: true
      - build:
          name: tests_integration
          load_docker_cache: true
          save_docker_cache: false
          run_tests_integration: true
          requires:
            - setup
      - build:
          name: tests_core
          load_docker_cache: true
          save_docker_cache: false
          run_tests_core: true
          requires:
            - setup
      - build:
          name: tests_internal
          load_docker_cache: true
          save_docker_cache: false
          run_tests_internal: true
          requires:
            - setup
      - build:
          name: tests_contrib
          load_docker_cache: true
          save_docker_cache: false
          run_tests_contrib: true
          requires:
            - setup

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - spcgeonode-release
    jobs:
      - build:
          load_docker_cache: false
          save_docker_cache: true
          run_tests_smoke: true
          run_tests_core: true
          run_tests_internal: true
          run_tests_contrib: true
          run_tests_integration: true
